turbot/steampipe-plugin-azure

- azure/service.go
> Fix error handling when the password got changed or the credentials got expired. Closes #8

- azure-test/tests/azure_cosmosdb_account/test-get-expected.json
- azure-test/tests/azure_cosmosdb_mongo_database/test-get-expected.json
- azure-test/tests/azure_cosmosdb_mongo_database/test-hydrate-expected.json
- azure-test/tests/azure_cosmosdb_sql_database/test-get-expected.json
- azure-test/tests/azure_cosmosdb_sql_database/test-hydrate-expected.json
- azure-test/tests/azure_resource_group/variables.tf
- azure/table_azure_ad_group.go
- azure/table_azure_ad_service_principal.go
- azure/table_azure_ad_user.go
- azure/table_azure_cosmosdb_account.go
- azure/table_azure_cosmosdb_mongo_database.go
- azure/table_azure_cosmosdb_sql_database.go
- azure/table_azure_management_lock.go
- azure/table_azure_provider.go
- azure/table_azure_resource_group.go
- azure/table_azure_role_assignment.go
- azure/table_azure_role_definition.go
- azure/table_azure_storage_account.go
- azure/table_azure_storage_queue.go
- azure/table_azure_subnet.go
`Tables modified`
- azure_ad_group
- azure_ad_service_principal
- azure_ad_user
- azure_cosmosdb_account
- azure_cosmosdb_mongo_database
- azure_cosmosdb_sql_database
- azure_management_lock
- azure_provider
- azure_resource_group
- azure_role_assignment
- azure_role_definition
- azure_storage_account
- azure_storage_queue
- azure_subnet
> Remove deprecated ItemFromKey from GET call. Closes #39

- docs/tables/azure_app_service_web_app.md
- go.mod
- go.sum
<details>
```
N/A
```
</details>
<details>
```sql
select
name,
outbound_ip_addresses,
possible_outbound_ip_addresses
from
azure_app_service_web_app;
```
```
+----------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name           | outbound_ip_addresses                                                   | possible_outbound_ip_addresses …
```
> [FIX] Typo in example query heading and updated the query to change region from location. Closes #33 Closes #34

- azure/table_azure_compute_virtual_machine.go
<details>
```
```
</details>
<details>
```
> select jsonb_pretty(extensions) as extensions from azure_compute_virtual_machine;
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| extensions                                                                                                                                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [ …
```
> Add further extension to the Azure VM table to support security feature query. closes #46

- docs/tables/azure_storage_container.md
<details>
```
```
</details>
<details>
```
select
name,
id,
type,
account_name,
public_access
from
azure_storage_container
where
public_access <> 'None';
+------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------
| name | id                                                                                                                                                                                    | type       
+------+------------------------------------------------------------------------------------------------------------------------------------------ …
```
> Example update for azure_storage_container table. Closes #113

- azure/table_azure_eventgrid_domain.go
<details>
```
SETUP: tests/azure_eventgrid_domain []
PRETEST: tests/azure_eventgrid_domain
TEST: tests/azure_eventgrid_domain
azurerm_resource_group.named_test_resource: Creation complete after 3s [id=/subscriptions/d46d7416-f95f-4771-bbb5-529d4c76659c/resourceGroups/turbottest7528]
azurerm_eventgrid_domain.named_test_resource: Creating...
azurerm_eventgrid_domain.named_test_resource: Still …
```
> Fix the columns in azure_eventgrid_domain table closes #354

- azure/table_azure_app_service_environment.go
- docs/tables/azure_app_service_environment.md
<details>
```
arnab@turbotindias-MacBook-Pro steampipe-plugin-azure % ./tint.js azure_app_service_environment
zsh: no such file or directory: ./tint.js
arnab@turbotindias-MacBook-Pro steampipe-plugin-azure % cd azure-test                          
arnab@turbotindias-MacBook-Pro azure-test % ./tint.js azure_app_service_environment
SETUP: tests/azure_app_service_environment []
PRETEST: tests/azure_app_service_environment
TEST: tests/azure_app_service_environment
plan. Resource actions …
```
> Add cluster_settings column in azure_app_service_environment table. Closes #318

- azure/service.go
- azure/table_azure_ad_group.go
- azure/table_azure_ad_service_principal.go
- azure/table_azure_ad_user.go
…wn desc = graphrbac.UsersClient#List: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF
<details>
```
```
</details>
<details>
```
```
</details>
> Fix azure_ad_* tables for connection 'azure': rpc error: code Fixes #412

- azure/table_azure_storage_container.go
- docs/tables/azure_storage_container.md
<details>
```
> select
name,
account_name,
jsonb_pretty(immutability_policy) as immutability_policy
from
azure_storage_container;
+-------------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------
| name                          | account_name           | immutability_policy                                                                                                                              
+-------------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------
| …
```
> Add missing API call to get immutability_policy in azure_storage_container. Fixes #433

- azure/table_azure_compute_virtual_machine_scale_set_vm.go
<details>
```
```
</details>
<details>
```
```
</details>
> Remove subscription_id column in azure_compute_virtual_machine_scale_set_vm table.

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.24.0

- azure/table_azure_storage_share_file.go
<details>
```
N/A
```
</details>
<details>
```
> select name, kind from azure_storage_account
+------------------------+------------------+
| name                   | kind             |
+------------------------+------------------+
| test45567788           | BlockBlobStorage |
| test0957498290         | StorageV2        |
| testimmutablecontainer | StorageV2        |
+------------------------+------------------+
```
```
> select * from azure_storage_share_file
+------+----------------------+----+------+-------------+-------------------------+--------------------+--------------------+---------+--------------+-------------------+------
| name | storage_account_name | id | type | access_tier | access_tier_change_time | access_tier_status | …
```
> Fix azure_storage_share_file File is not supported for the storage account closes #474

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.27.2

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Update CHANGELOG for v0.28.0 release

- azure/table_azure_app_service_plan.go
<details>
```
```
</details>
<details>
```
> select jsonb_pretty(apps) from azure_app_service_plan
+------------------------------------------------------------------------------------------------------------------------------------------+
| jsonb_pretty                                                                                                                             |
+------------------------------------------------------------------------------------------------------------------------------------------+
| [                                                                                                                                        |
|     { …
```
> Extract properties of apps column in table azure_app_service_plan closes #539

- azure/service.go
- azure/table_azure_api_management.go
- azure/table_azure_compute_resource_sku.go
- azure/table_azure_compute_virtual_machine.go
- azure/table_azure_diagnostic_setting.go
- azure/table_azure_mssql_managed_instance.go
- azure/table_azure_mysql_flexible_server.go
<details>
```
```
</details>
<details>
```
```
</details>
> Fix capabilities, resourceLocation, restrictions and costs column in azure_compute_resource_sku table

- azure/table_azure_compute_resource_sku.go
<details>
```
```
</details>
<details>
```
```
</details>
> Remove commented code in `azure_compute_resource_sku` table

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.34.1

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.34.2

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.35.1

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.37.0

- azure/table_azure_cosmosdb_mongo_database.go
- docs/tables/azure_cosmosdb_mongo_database.md
<details>
```
```
</details>
<details>
```sql
> select
throughput_settings ->> 'Name' as name,
throughput_settings ->> 'ResourceThroughput' as throughput,
throughput_settings ->> 'AutoscaleSettingsMaxThroughput' as maximum_throughput,
throughput_settings ->> 'ResourceMinimumThroughput' as minimum_throughput,
throughput_settings ->> 'ID' as id
from
azure_cosmosdb_mongo_database;
+------+------------+--------------------+--------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name | throughput | maximum_throughput | minimum_throughput | …
```
> Add column `throughput_settings` to table `azure_cosmosdb_mongo_database`. Closes #586

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.42.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.44.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.45.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.45.1

- azure/plugin.go
- azure/table_azure_container_group.go
- docs/tables/azure_container_group.md
<details>
```
```
</details>
<details>
```
select
name,
id,
provisioning_state,
restart_policy,
sku,
region
from
azure_container_group;
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+----------->
| name                    | id                                                                                                                                                    | provisioning_state | restart_po>
+-------------------------+------------------------------------------------------------------------------------------------------------------------- …
```
> Add table azure_container_group Closes #632

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.46.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.47.0

- azure/table_azure_eventgrid_domain.go
<details>
```
```
</details>
<details>
```sql
> select name, disable_local_auth from azure_eventgrid_domain
[
{
"disable_local_auth": false,
"name": "demo-test"
}
]
```
</details>
> Fix `disable_local_auth` column in `azure_eventgrid_domain` table. Closes #648

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.48.0

- docs/index.md
<details>
```
```
</details>
<details>
```
```
</details>
> Update the docs to use latest Steampipe definition

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.52.0

- .github/workflows/registry-publish.yml
- .github/workflows/steampipe-anywhere.yml
<details>
```
```
</details>
<details>
```
```
</details>
> Update workflows to use large runners

- .github/workflows/steampipe-anywhere.yml
<details>
```
```
</details>
<details>
```
```
</details>
> Update steampipe-anywhere.yml to use local definition to support larger runner

- .github/workflows/registry-publish.yml
- .github/workflows/steampipe-anywhere.yml
<details>
```
```
</details>
<details>
```
```
</details>
> Update the runners for Release workflows

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.54.0

- .github/workflows/registry-publish-ghcr.yml
<details>
```
```
</details>
<details>
```
```
</details>
> Add Build and Deploy OCI Image - GHCR workflow

- .github/workflows/steampipe-anywhere.yml
<details>
```
```
</details>
<details>
```
```
</details>
>  Add test installation steps to the Steampipe Anywhere components workflow

- azure-test/tint.js
<details>
```
```
</details>
<details>
```
```
</details>
> Fixed the integration test script as per the latest Steampipe CLI result

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.58.0

- azure/plugin.go
- azure/table_azure_data_protection_backup_job.go
- docs/tables/azure_data_protection_backup_job.md
<details>
```
N/A
```
</details>
<details>
```
> select * from azure_data_protection_backup_job
{
"rows": [
{
"_ctx": {
"connection_name": "azure",
"steampipe": {
"sdk_version": "5.10.1"
}
},
"activity_id": "3c59479b-3a7e-4e7b-aa8a-da0b6dd7d04a-Ibz",
"akas": [
"azure:///subscriptions/********-****-****-****-************/resourceGroups/turbottest85362/providers/Microsoft.DataProtection/backupVaults/turbottest85362/backupJobs/9c395c24-ce22-4724-a1db-ad6321606c89",
"azure:///subscriptions/********-****-****-****-************/resourcegroups/turbottest85362/providers/microsoft.dataprotection/backupvaults/turbottest85362/backupjobs/9c395c24-ce22-4724-a1db-ad6321606c89"
],
"backup_instance_friendly_name": "turbottest85362",
"backup_instance_id": …
```
> Add table azure_data_protection_backup_job Closes #782

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.59.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.60.0

- azure/service.go
- config/azure.spc
- docs/index.md
<details>
```
```
</details>
<details>
```
```
</details>
> Updated the doc based on Azure SDK authentication for different environment

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.62.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.63.0

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.64.0

- azure/table_azure_application_gateway.go
<details>
```
```
</details>
<details>
```
> select name,firewall_policy,  jsonb_pretty(web_application_firewall_configuration) from azure_application_gateway
+----------+-----------------+-----------------------------------+
| name     | firewall_policy | jsonb_pretty                      |
+----------+-----------------+-----------------------------------+
| test5333 | <null>          | {                                 |
|          |                 |     "enabled": true,              |
|          |                 |     "exclusions": [               |
|          |                 |     ],                            |
|          |                 |     "ruleSetType": "OWASP",       |
|          | …
```
> Removed the extra API call to populate the `web_application_firewall_configuration` column value in the table `azure_application_gateway` Closes #825

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v0.65.0

- CHANGELOG.md
- azure/service.go
<details>
```
```
</details>
<details>
```
steampipe query "select * from azure_all.azure_role_assignment limit 5;"
+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+-----------------------------------------+--------------------------------------+------------------+---------------------------+---------------------------+------------------------------------------------------------------------------------------------------------------------------------- …
```
> fix: Prevent the subscription ID being overwritten with the default one from Azure CLI when using CLI authentication.

- azure-test/package-lock.json
- azure/table_azure_storage_account.go
```
-- Public Network Access Check
select
sa.id as resource,
case
when public_network_access = 'Disabled' then 'ok'
else 'alarm'
end as status,
case
when public_network_access = 'Disabled' then sa.name || ' public network access is disabled.'
else sa.name || ' public network access is enabled.'
end as reason
from
azure_storage_account sa,
azure_subscription sub
where
sub.subscription_id = sa.subscription_id;
+------------------------------------------------------------------------------------------------+--------+------------------------------------------------+
| resource                                                                                         | status | reason                                           |
+--------------------------------------------------------------------- …
```
> Add Support for Additional Azure Storage Account Properties

- azure/plugin.go
- azure/table_azure_network_profile.go
- docs/tables/azure_network_profile.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add table azure_network_profile

- azure/table_azure_key_vault.go
<details>
```
N/A
```
</details>
<details>
```
> select name, jsonb_pretty(diagnostic_settings) from azure_key_vault
+--------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name         | jsonb_pretty                                                                                                                                                                                   |
+--------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| …
```
> Fix diagnostic_settings column in azure_key_vault table to correctly return data instead of null Closes #914

- azure/table_azure_app_service_web_app.go
…
<details>
```
```
</details>
<details>
```
> select name, jsonb_pretty(diagnostic_settings) from azure_app_service_web_app
+-----------------+---------------------------------------------------------------------------------------------------------------------------------->
| name            | jsonb_pretty                                                                                                                     >
+-----------------+---------------------------------------------------------------------------------------------------------------------------------->
| test-deleet-web | [ …
```
> Add diagnostic_settings column in table azure_app_service_web_app closes #920

- CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
> Add CHANGELOG for v1.5.0

- azure/table_azure_databricks_workspace.go
- docs/tables/azure_databricks_workspace.md
<details>
```
```
</details>
<details>
```
```
</details>
> Added column diagnostic_settings to the table azure_databricks_workspace Closes #928

- azure/plugin.go
The default rate limiter configuration has been added for the following tables:
- azure_subscription
- azure_resource_group
- azure_compute_virtual_machine
- azure_storage_account
- azure_storage_blob
- azure_key_vault_secret
- azure_key_vault_key
- azure_monitor_activity_log
> Added default rate limit configuration for the tables
