- CHANGELOG.md
_Bug fixes_
- Recompiled plugin with latest [steampipe-plugin-sdk](https://github.com/turbot/steampipe-plugin-sdk) to resolve issue:
- Fix tables failing with error similar to `Error: pq: rpc error: code = Internal desc = get hydrate function getAdGroup failed with panic interface conversion: interface {} is nil, not *graphrbac.ADGroup`([#29](https://github.com/turbot/steampipe-plugin-azure/issues/29)).
> Add CHANGELOG for v0.2.2. Closes #31

- azure-test/tests/azure_sql_server/test-hydrate-expected.json
- azure/table_azure_sql_server.go
- docs/tables/azure_sql_server.md
<details>
```
SETUP: tests/azure_sql_server []
PRETEST: tests/azure_sql_server
TEST: tests/azure_sql_server
azurerm_resource_group.named_test_resource: Creation complete after 3s [id=/subscriptions/********-****-****-****-************/resourceGroups/turbottest95686]
azurerm_storage_account.named_test_resource: Still creating... [10s elapsed] …
```
> Update table azure_sql_server to return null instead of empty object, if not configured. Closes #67

- azure/table_azure_storage_account.go
<details>
```
N/A
```
</details>
<details>
```sql
select
name,
blob_service_logging ->> 'Read' as logging_read,
blob_service_logging ->> 'Write' as logging_write,
blob_service_logging ->> 'Delete' as logging_delete
from 
azure_storage_account
where
(blob_service_logging ->> 'Read')::boolean
and (blob_service_logging ->> 'Write')::boolean
and (blob_service_logging ->> 'Delete')::boolean;
```
```
+-----------+--------------+---------------+----------------+
| name      | logging_read | logging_write | logging_delete |
+-----------+--------------+---------------+----------------+
| test123aq | true         | true          | true           |
+-----------+--------------+---------------+----------------+
```
</details>
> Update azure_storage_account table to include blob service logging details. Closes #79

- azure-test/tests/azure_key_vault/variables.tf
- azure/table_azure_key_vault.go
- docs/tables/azure_key_vault.md
<details>
```
SETUP: tests/azure_key_vault []
PRETEST: tests/azure_key_vault
TEST: tests/azure_key_vault
azurerm_resource_group.named_test_resource: Creation complete after 5s [id=/subscriptions/********-****-****-****-************/resourceGroups/turbottest35668]
azurerm_key_vault.named_test_resource: Creating...
azurerm_key_vault.named_test_resource: Still creating... [10s elapsed] …
```
> [FIX] Azure query for Key Vault runs to infinite loop. Closes #35

- azure-test/tests/azure_key_vault/test-logging-expected.json
- azure-test/tests/azure_key_vault/test-logging-query.sql
- azure-test/tests/azure_key_vault/variables.tf
- azure/table_azure_key_vault.go
- docs/tables/azure_key_vault.md
<details>
```
SETUP: tests/azure_key_vault []
PRETEST: tests/azure_key_vault
TEST: tests/azure_key_vault
azurerm_key_vault.named_test_resource: Creating...
azurerm_key_vault.named_test_resource: Still creating... [10s elapsed]
azurerm_storage_account.named_test_resource: Still creating... [10s elapsed]
azurerm_storage_account.named_test_resource: Still creating... [20s elapsed] …
```
> Add support to query logging information for key vault. Closes #95

- azure/table_azure_diagnostic_setting.go
<details>
```
```
</details>
<details>
```
select resource_group, subscription_id from azure_diagnostic_setting;
+----------------+--------------------------------------+
| resource_group | subscription_id                      |
+----------------+--------------------------------------+
| turbot_rg      | d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8 |
| turbot_rg      | d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8 |
| turbot_rg      | d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8 |
+----------------+--------------------------------------+
select resource_group, subscription_id from azure_diagnostic_setting;
+----------------+--------------------------------------+
| resource_group | subscription_id                      | …
```
> [Fix] subscription_id column not displaying wrong value in azure_diagnostic_setting table. Closes #98

- azure-test/tests/azure_storage_container/test-get-expected.json
- azure/table_azure_storage_container.go
<details>
```
SETUP: tests/azure_storage_container []
PRETEST: tests/azure_storage_container
TEST: tests/azure_storage_container
azurerm_resource_group.named_test_resource: Creation complete after 8s [id=/subscriptions/d46d7416-f95f-4771-bbb5-529d4c76659c/resourceGroups/turbottest97526]
azurerm_storage_account.named_test_resource: Still …
```
> Getting an error cannot convert 2021-04-23T11:28:02Z to a time.Time in azure_storage_container table. Closes #102

- azure/table_azure_storage_account.go
- azure/utils.go
…e.Time in table azure_storage_account table. Closes #100
<details>
```
```
</details>
<details>
```
select name, encryption_key_vault_properties_last_rotation_time from azure_storage_account;
+---------+----------------------------------------------------+
| name    | encryption_key_vault_properties_last_rotation_time |
+---------+----------------------------------------------------+
| test007 | 2021-04-23 12:10:50                                |
+---------+----------------------------------------------------+
```
</details>
> [Fix] Getting error `cannot convert 2021-04-23T11:33:12.8437526Z to a time.Time` in azure_storage_account. Closes #100

- azure/table_azure_compute_virtual_machine.go
<details>
```
azurerm_resource_group.named_test_resource: Creation complete after 2s [id=/subscriptions/cd4401c4-3cc8-4565-a594-839c1e345f1e/resourceGroups/turbottest69292]
azurerm_virtual_network.named_test_resource: Creating...
azurerm_virtual_network.named_test_resource: Creation complete after 9s [id=/subscriptions/cd4401c4-3cc8-4565-a594-839c1e345f1e/resourceGroups/tu …
```
> Add support for VHD (Virtual Hard Disks) encryption check. closes #50

- azure/service.go
<details>
```
```
</details>
<details>
```
```
</details>
> Error message is not clear enough to state what goes wrong with the command. Closes #109

- azure-test/tests/azure_policy_definition/test-list-expected.json
- azure-test/tests/azure_policy_definition/test-list-query.sql
- azure-test/tests/azure_policy_definition/variables.tf
- azure/plugin.go
- azure/table_azure_policy_definition.go
- docs/tables/azure_policy_definition.md
<details>
```
pskrbasu@Puskars-MacBook-Pro azure-test (main) $ ./tint.js tests/azure_policy_definition
SETUP: tests/azure_policy_definition []
PRETEST: tests/azure_policy_definition
TEST: tests/azure_policy_definition
azurerm_policy_definition.named_test_resource: Creating...
azurerm_policy_definition.named_test_resource: Still creating... [10s elapsed]
azurerm_policy_definition.named_test_resource: Still creating... [20s elapsed] …
```
> Add table azure_policy_definition. closes #18

- azure/table_azure_storage_account.go
- docs/tables/azure_storage_account.md
<details>
```
SETUP: tests/azure_storage_account []
PRETEST: tests/azure_storage_account
TEST: tests/azure_storage_account
azurerm_resource_group.named_test_resource: Creation complete after 3s [id=/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/turbottest43097]
azurerm_storage_account.named_test_resource: Still creating... …
```
> Add lifecycle_management_policy details for storage account. Closes #146

- azure/table_azure_virtual_network_gateway.go
**_Bug Fixes_**
- Earlier network gateway resource has dependency on `virtual network` resource, hence table stores duplicate resources, whenever more than one `virtual network` resource is present in a resourceGroup.
Currently, the dependency has been updated, to list the resource based on available `resource group`.
`Earlier Response`
```
> select name, id from azure_virtual_network_gateway;
+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+
| name               | id                                                                                                                                                  | …
```
> Changing parent to resourceGroup to remove duplicate network gateway entry. Closes #180

- azure/plugin.go
- azure/table_azure_security_center_jit_network_access_policy.go
- docs/tables/azure_security_center_jit_network_access_policy.md
<details>
```
This resource doesn't have any terraform support, also don't have any CLI command to enable it.
```
</details>
<details>
```sql
select
vm.name,
vm.id,
jsonb_pretty(vms -> 'ports') as ports
from
azure_security_center_jit_network_access_policy,
jsonb_array_elements(virtual_machines) as vms,
azure_compute_virtual_machine as vm
where
lower(vms ->> 'id') = lower(vm.id);
```
```
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------+
| name            | id …
```
> Add table azure_security_center_jit_network_access_policy. Closes #191

- azure/table_azure_key_vault.go
<details>
```
SETUP: tests/azure_key_vault []
PRETEST: tests/azure_key_vault
TEST: tests/azure_key_vault
azurerm_resource_group.named_test_resource: Creation complete after 5s [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest55219]
azurerm_key_vault.named_test_resource: Creating...
azurerm_key_vault.named_test_resource: Still creating... [10s elapsed]
azurerm_storage_account.named_test_resource: Still creating... [10s elapsed]
azurerm_key_vault.named_test_resource: Still creating... [20s elapsed]
azurerm_storage_account.named_test_resource: Still creating... [21s elapsed] …
```
> Add NetworkAcls details in table azure_key_vault.Closes #208

- azure/table_azure_eventhub_namespace.go
<details>
```
SETUP: tests/azure_eventhub_namespace []
PRETEST: tests/azure_eventhub_namespace
TEST: tests/azure_eventhub_namespace
azurerm_resource_group.named_test_resource: Creation complete after 2s [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest24299]
azurerm_eventhub_namespace.named_test_resource: Creating...
azurerm_eventhub_namespace.named_test_resource: Still creating... [10s elapsed]
azurerm_eventhub_namespace.named_test_resource: Still creating... [20s elapsed]
azurerm_eventhub_namespace.named_test_resource: Still creating... [30s elapsed]
azurerm_eventhub_namespace.named_test_resource: Still creating... [40s elapsed] …
```
> Add Diagnostic settings details in table azure_eventhub_namespace. Closes #212

- azure/table_azure_servicebus_namespace.go
<details>
```
SETUP: tests/azure_servicebus_namespace []
PRETEST: tests/azure_servicebus_namespace
TEST: tests/azure_servicebus_namespace
azurerm_resource_group.named_test_resource: Creation complete after 5s [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest35576]
azurerm_servicebus_namespace.named_test_resource: Creating...
azurerm_servicebus_namespace.named_test_resource: Still creating... [10s elapsed]
azurerm_servicebus_namespace.named_test_resource: Still creating... [20s elapsed]
azurerm_servicebus_namespace.named_test_resource: Still creating... [30s elapsed]
azurerm_servicebus_namespace.named_test_resource: Still creating... [40s elapsed] …
```
> Add Diagnostic settings details in table azure_servicebus_namespace. Closes #215

- azure/table_azure_sql_server.go
<details>
```
SETUP: tests/azure_sql_server []
PRETEST: tests/azure_sql_server
TEST: tests/azure_sql_server
azurerm_resource_group.named_test_resource: Creation complete after 4s [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest93390]
azurerm_storage_account.named_test_resource: Still creating... [10s elapsed]
azurerm_storage_account.named_test_resource: Still creating... [20s elapsed]
azurerm_storage_account.named_test_resource: Still creating... [30s elapsed]
azurerm_storage_account.named_test_resource: Creation complete after 37s [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/tur …
```
> Add Virtual Network Rules details in table azure_sql_server. Closes #210

- azure/table_azure_compute_virtual_machine.go
<details>
```
azurerm_resource_group.named_test_resource: Creation complete after 3s [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest32867]
azurerm_virtual_network.named_test_resource: Creating... …
```
> Add type details of extensions for table azure_compute_virtual_machine closes #216

- azure-test/tests/azure_sql_server/test-hydrate-expected.json
- azure-test/tests/azure_sql_server/variables.tf
- azure/table_azure_sql_server.go
<details>
```
SETUP: tests/azure_sql_server []
PRETEST: tests/azure_sql_server
TEST: tests/azure_sql_server
azurerm_resource_group.named_test_resource: Creation complete after 2s [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest72057]
azurerm_storage_account.named_test_resource: Still creating... [10s …
```
> Not getting firewall_rules for table azure_sql_server. closes #228

- azure/table_azure_network_security_group.go
<details>
```
SETUP: tests/azure_network_security_group []
PRETEST: tests/azure_network_security_group
TEST: tests/azure_network_security_group
azurerm_resource_group.named_test_resource: Creation complete after 3s [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest14666]
azurerm_network_security_group.named_test_resource: Creating...
azurerm_network_security_group.named_test_resource: Still creating... [10s elapsed]
azurerm_network_security_group.named_test_resource: Creation complete after 11s [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest14666/providers/Microsoft.Network/networkSecurityGroups/turbottest14666]
Warning: Version …
```
> Add `diagnostic_settings` column in `azure_network_security_group` table. Closes #244

- azure-test/tests/azure_sql_database/test-get-query.sql
- azure/table_azure_compute_virtual_machine.go
- azure/table_azure_sql_database.go
<details>
```
SETUP: tests/azure_sql_database []
PRETEST: tests/azure_sql_database
TEST: tests/azure_sql_database
azurerm_resource_group.named_test_resource: Creation complete after 2s [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest33097]
azurerm_sql_server.named_test_resource: Creating...
azurerm_sql_server.named_test_resource: Still creating... [10s elapsed] …
```
> Add Long Term Retention Policies details in table azure_sql_database closes #219

- azure-test/tests/azure_api_management/variables.tf
- azure-test/tests/azure_app_service_function_app/test-hydrate-expected.json
- azure-test/tests/azure_app_service_plan/test-hydrate-expected.json
- azure-test/tests/azure_app_service_web_app/test-get-expected.json
- azure-test/tests/azure_app_service_web_app/test-hydrate-expected.json
- azure-test/tests/azure_app_service_web_app/test-list-expected.json
- azure-test/tests/azure_app_service_web_app/test-turbot-expected.json
- azure-test/tests/azure_compute_disk_encryption_set/test-get-expected.json
- azure-test/tests/azure_compute_disk_encryption_set/test-get-query.sql
- azure-test/tests/azure_compute_disk_encryption_set/test-hydrate-expected.json
- azure-test/tests/azure_compute_disk_encryption_set/test-hydrate-query.sql
- azure-test/tests/azure_compute_disk_encryption_set/variables.tf
- azure-test/tests/azure_virtual_network/test-get-expected.json
- azure/table_azure_data_factory_dataset.go
<details>
```  
SETUP: tests/azure_data_factory_dataset []
PRETEST: tests/azure_data_factory_dataset
TEST: tests/azure_data_factory_dataset
azurerm_resource_group.named_test_resource: Refreshing state... [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest48840]
azurerm_data_factory.named_test_resource: Refreshing state... [id=/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/resourceGroups/turbottest48840/providers/Microsoft.DataFactory/factories/turbottest48840] …
```
> Fix Integration test failed for resources. Closes #258

- azure/table_azure_sql_database.go
<details>
```
SETUP: tests/azure_sql_database []
PRETEST: tests/azure_sql_database
TEST: tests/azure_sql_database
+ create
+ id       = (known after apply)
+ location = "eastus"
+ name     = "turbottest7322"
}
+ resource "azurerm_sql_database" "named_test_resource" {
+ collation                        = (known after apply)
+ create_mode                      = "Default"
+ creation_date                    = (known after apply)
+ default_secondary_location       = (known after apply)
+ edition …
```
> Add column `vulnerability_assessments` and `vulnerability_assessment_scan_records` in table azure_sql_database #273

- azure/table_azure_data_factory.go
<details>
```
SETUP: tests/azure_data_factory []
PRETEST: tests/azure_data_factory
TEST: tests/azure_data_factory
azurerm_resource_group.named_test_resource: Creation complete after 2s [id=/subscriptions/d46d7416-f95f-4771-bbb5-529d4c76659c/resourceGroups/turbottest45505]
azurerm_data_factory.named_test_resource: Creating...
azurerm_data_factory.named_test_resource: Still creating... [10s …
```
> Add Private Endpoint Connection details in table azure_data_factory closes #285

- azure/table_azure_sql_server.go
<details>
```
SETUP: tests/azure_sql_server []
PRETEST: tests/azure_sql_server
TEST: tests/azure_sql_server
azurerm_resource_group.named_test_resource: Creation complete after 3s [id=/subscriptions/d46d7416-f95f-4771-bbb5-529d4c76659c/resourceGroups/turbottest57916]
azurerm_storage_account.named_test_resource: Still creating... [10s …
```
> Add Private Endpoint Connection details in table azure_sql_server closes #289

- azure/table_azure_postgresql_server.go
<details>
```
SETUP: tests/azure_postgresql_server []
PRETEST: tests/azure_postgresql_server
TEST: tests/azure_postgresql_server
azurerm_resource_group.named_test_resource: Creation complete after 5s [id=/subscriptions/d46d7416-f95f-4771-bbb5-529d4c76659c/resourceGroups/turbottest62688]
azurerm_postgresql_server.named_test_resource: Creating...
azurerm_postgresql_server.named_test_resource: Still …
```
> Add server keys details in table azure_postgresql_server closes #287

- azure-test/tests/azure_key_vault/test-hydrate-expected.json
- azure/table_azure_key_vault.go
- docs/tables/azure_key_vault.md
<details>
```
arnab@turbotindias-MacBook-Pro azure-test % ./tint.js azure_key_vault
SETUP: tests/azure_key_vault []
PRETEST: tests/azure_key_vault
TEST: tests/azure_key_vault
+ create
+ resource "azurerm_key_vault" "named_test_resource" {
+ access_policy              = (known after apply)
+ id                         = (known after apply)
+ location                   = …
```
> Fix table azure_key_vault failed to populate column private_endpoint_connections issue. Closes #340

- azure/table_azure_compute_virtual_machine.go
- docs/tables/azure_compute_virtual_machine.md
<details>
```
arnab@turbotindias-MacBook-Pro azure-test % ./tint.js azure_compute_virtual_machine
+ create
+ resource "azurerm_network_interface" "named_test_resource" {
+ applied_dns_servers           = (known after apply)
+ dns_servers …
```
> Add VirtualMachineIdentity details in table azure_compute_virtual_machine. Closes #321

- azure/table_azure_postgresql_server.go
- docs/tables/azure_postgresql_server.md
<details>
```
arnab@turbotindias-MacBook-Pro azure-test % ./tint.js azure_postgresql_server
SETUP: tests/azure_postgresql_server []
PRETEST: tests/azure_postgresql_server
TEST: tests/azure_postgresql_server
+ create
+ resource "azurerm_postgresql_active_directory_administrator" "named_test_resource" {
+ id                  = (known after apply)
+ login               = …
```
> Fix private_endpoint_connections column for table azure_postgresql_server. Closes #309

- azure-test/tests/azure_mysql_server/test-get-expected.json
- azure-test/tests/azure_mysql_server/variables.tf
- azure/table_azure_mysql_server.go
- docs/tables/azure_mysql_server.md
<details>
```
arnab@turbotindias-MacBook-Pro azure-test % ./tint.js azure_mysql_server
SETUP: tests/azure_mysql_server []
PRETEST: tests/azure_mysql_server
TEST: tests/azure_mysql_server
+ create
+ resource "azurerm_mysql_server" "named_test_resource" {
+ administrator_login               = "mradministrator"
+ administrator_login_password      = (sensitive value)
+ …
```
> Fix private_endpoint_connections column for table azure_mysql_server. Closes #304

- azure/table_azure_servicebus_namespace.go
- docs/tables/azure_servicebus_namespace.md
<details>
```
arnab@turbotindias-MacBook-Pro azure-test % ./tint.js azure_servicebus_namespace                                                                                      
SETUP: tests/azure_servicebus_namespace []
PRETEST: tests/azure_servicebus_namespace
TEST: tests/azure_servicebus_namespace
+ create
+ id …
```
> Add Private Endpoint Connection details in table azure_servicebus_namespace. Closes #295

- azure/table_azure_eventhub_namespace.go
- docs/tables/azure_eventhub_namespace.md
<details>
```
arnab@turbotindias-MacBook-Pro azure-test % ./tint.js azure_eventhub_namespace
SETUP: tests/azure_eventhub_namespace []
PRETEST: tests/azure_eventhub_namespace
TEST: tests/azure_eventhub_namespace
+ create
+ resource "azurerm_eventhub_namespace" "named_test_resource" {
+ auto_inflate_enabled                = false
+ capacity                            = 1
+ …
```
> Add Private Endpoint Connection details in table azure_eventhub_namespace. Closes #303

- azure/table_azure_mssql_managed_instance.go
- docs/tables/azure_mssql_managed_instance.md
<details>
```
> select
name,
id,
state,
license_type,
minimal_tls_version
from
azure_mssql_managed_instance;
+-----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+-------------
| name                  | id                                                                                                                                                          | state | license_type
+-----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+-------------
| test-managed-instance | …
```
> Add security_alert_policies column in azure_mssql_managed_instance table. Closes #291

- azure/table_azure_eventhub_namespace.go
<details>
```
arnab@turbotindias-MacBook-Pro azure-test % ./tint.js azure_eventhub_namespace
SETUP: tests/azure_eventhub_namespace []
PRETEST: tests/azure_eventhub_namespace
TEST: tests/azure_eventhub_namespace
+ create
+ resource "azurerm_eventhub_namespace" "named_test_resource" {
+ auto_inflate_enabled                = false
+ capacity                            = 1
+ …
```
> Fix getting null value for column cluster_arm_id in table azure_eventhub_namespace. Closes #323

- azure/table_azure_sql_server.go
<details>
```
> select jsonb_pretty(encryption_protector) from azure_sql_server
+----------------------------------------------------------------------------------------------------------------------------------------------
| jsonb_pretty                                                                                                                                 
+----------------------------------------------------------------------------------------------------------------------------------------------
| [                                                                                                                                            
|     { …
```
> Add missing properties of encryption_protector  column in azure_sql_server table. Closes #335

- azure/table_azure_sql_server.go
<details>
```
> select jsonb_pretty(server_vulnerability_assessment) as server_vulnerability_assessment, jsonb_pretty(private_endpoint_connections) from azure_sql_server
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_vulnerability_assessment                                                                                                                                         | jsonb_pretty …
```
> Add public_network_access and minimal_tls_version column in azure_sql_server table.

- azure/table_azure_app_configuration.go
<details>
```
> select name,public_network_access,private_endpoint_connections from azure_app_configuration
+--------------------+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| name               | public_network_access | private_endpoint_connections                                                                                                                                                                                                     
+--------------------+-----------------------+------------------------------------------------------------------------- …
```
> Add hydrate function to determine the default value for public_network_access column in azure_app_configuration table #364

- azure/table_azure_kusto_cluster.go
<details>
```
SETUP: tests/azure_kusto_cluster []
PRETEST: tests/azure_kusto_cluster
TEST: tests/azure_kusto_cluster
azurerm_resource_group.named_test_resource: Creation complete after 3s [id=/subscriptions/d46d7416-f95f-4771-bbb5-529d4c76659c/resourceGroups/turbottest69065]
azurerm_kusto_cluster.named_test_resource: Creating...
azurerm_kusto_cluster.named_test_resource: Still creating... [10s …
```
> Add encryption properties in azure_kusto_cluster table closes #373

- azure/table_azure_servicebus_namespace.go
- docs/tables/azure_servicebus_namespace.md
- go.mod
- go.sum
<details>
```
arnab@turbotindias-MacBook-Pro azure-test % ./tint.js azure_servicebus_namespace
SETUP: tests/azure_servicebus_namespace []
PRETEST: tests/azure_servicebus_namespace
TEST: tests/azure_servicebus_namespace
+ create
+ id       = (known after apply)
+ location = "eastus"
+ name     = "turbottest93414"
}
+ …
```
> Fix azure_servicebus_namespace table break if encryption is set for servicebus namespace. Closes #332

- azure/table_azure_compute_virtual_machine.go
- docs/tables/azure_compute_virtual_machine.md
<details>
```
arnab@turbotindias-MacBook-Pro azure-test % ./tint.js azure_compute_virtual_machine
+ create
+ resource "azurerm_network_interface" "named_test_resource" {
+ applied_dns_servers           = (known after apply)
+ dns_servers …
```
> Add security_profile column in azure_compute_virtual_machine table. Closes #383

- azure/table_azure_compute_virtual_machine.go
- azure/table_azure_compute_virtual_machine_metric_cpu_utilization.go
- azure/table_azure_compute_virtual_machine_metric_cpu_utilization_daily.go
- azure/table_azure_compute_virtual_machine_metric_cpu_utilization_hourly.go
<details>
```
azurerm_resource_group.named_test_resource: Refreshing state... [id=/subscriptions/d46d7416-f95f-4771-bbb5-529d4c76659c/resourceGroups/turbottest68661]
azurerm_virtual_network.named_test_resource: Refreshing state... [id=/subscriptions/d46d7416-f95f-4771-bbb5-529d4c76659c/resourceGroups/turbottest68661/provi …
```
> Add os_name and os_version column in the azure_compute_virtual_machine table. closes #419

- azure/table_azure_storage_account.go
- azure/table_azure_storage_blob_service.go
- azure/table_azure_storage_container.go
- azure/table_azure_storage_queue.go
- azure/table_azure_storage_table.go
- azure/table_azure_storage_table_service.go
<details>
```
> select * from azure_storage_container
Error: storage.BlobContainersClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="FeatureNotSupportedForAccount" Message="Blob is not supported for the account."
> select * from azure_storage_account
Error: storage.BlobServicesClient#GetServiceProperties: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="FeatureNotSupportedForAccount" Message="Blob is not supported for the account."
> select * from azure_storage_blob_service
Error: storage.BlobServicesClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service …
```
> Added check for storage type FileStorage where blob is not supported in storage tables.

- azure/plugin.go
- azure/table_azure_compute_virtual_machine_scale_set_vm.go
- docs/tables/azure_compute_virtual_machine_scale_set_vm.md
<details>
```
Terraform does not support the resource.
```
</details>
<details>
```sql
select
name,
scale_set_name,
instance_id,
id,
vm_id,
region,
resource_group
from
azure_compute_virtual_machine_scale_set_vm;
```
```
+--------------------------------------+------------------------------------+-------------+---------------------------------------------------------------------------------------------------------------
| name                                 | scale_set_name                     | instance_id | id                                                                                                            
+--------------------------------------+------------------------------------+-------------+-------------------------------- …
```
> Add table azure_compute_virtual_machine_scale_set_vm closes #423

- azure-test/tests/azure_mysql_server/variables.tf
- azure/table_azure_mysql_server.go
- docs/tables/azure_mysql_server.md
<details>
```
SETUP: tests/azure_mysql_server []
PRETEST: tests/azure_mysql_server
TEST: tests/azure_mysql_server
+ create
+ resource "azurerm_mysql_server" "named_test_resource" {
+ administrator_login               = "mradministrator"
+ administrator_login_password      = (sensitive value)
+ auto_grow_enabled                 = false
+ backup_retention_days             = 7
+ create_mode                       = "Default"
+ fqdn                              = (known after apply)
+ geo_redundant_backup_enabled      = false
+ id                                = (known …
```
> Added column server_configurations in azure_mysql_server table. Closes #427

- azure/table_azure_storage_account.go
- docs/tables/azure_storage_account.md
<details>
```
SETUP: tests/azure_storage_account []
PRETEST: tests/azure_storage_account
TEST: tests/azure_storage_account
+ create
+ id       = (known after apply)
+ location = "eastus"
+ name     = "turbottest33803"
+ tags     = (known after apply)
}
+ resource "azurerm_storage_account" "named_test_resource" {
+ access_tier                       = "Cool"
+ account_encryption_source         = "Microsoft.Storage"
+ account_kind                      = "StorageV2"
+ account_replication_type          = "LRS"
+ …
```
> Added column diagnostic_settings to azure_storage_account table.

- azure/common_columns.go
- azure/monitoring_metric.go
- azure/service.go
- azure/table_azure_subscription.go
- azure/utils.go
<details>
```
```
</details>
<details>
```
select
name,
access_tier,
sku_name,
resource_group, cloud_environment
from
azure_storage_account;
+------------------------+-------------+----------------+----------------------------------+-------------------+
| name                   | access_tier | sku_name       | resource_group                   | cloud_environment |
+------------------------+-------------+----------------+----------------------------------+-------------------+
| csg10032000527a882b    | Hot         | Standard_LRS   | cloud-shell-storage-centralindia | AzurePublicCloud  |
| testimmutablecontainer | Hot         | Standard_RAGRS | nist-test_group                  | AzurePublicCloud  | …
```
> Rename column environment_name to cloud_environment

- azure/service.go
- docs/index.md
<details>
```
```
</details>
<details>
```
```
</details>
> Fix GetNewSession function to cache credentials session correctly. Fixes #441

- azure/table_azure_sql_database.go
- go.mod
<details>
```
SETUP: tests/azure_sql_database []
PRETEST: tests/azure_sql_database
TEST: tests/azure_sql_database
azurerm_resource_group.named_test_resource: Creation complete after 4s [id=/subscriptions/d46d7416-f95f-4771-bbb5-529d4c76659c/resourceGroups/turbottest92068]
azurerm_sql_server.named_test_resource: Creating...
azurerm_sql_server.named_test_resource: Still creating... [10s elapsed] …
```
> Change the column type for read_scale & create_mode in azure_sql_database. closes #454

- azure/table_azure_storage_queue.go
<details>
```
SETUP: tests/azure_storage_queue []
PRETEST: tests/azure_storage_queue
TEST: tests/azure_storage_queue
azurerm_resource_group.named_test_resource: Creation complete after 3s [id=/subscriptions/d46d7416-f95f-4771-bbb5-529d4c76659c/resourceGroups/turbottest91393]
azurerm_storage_account.named_test_resource: Still creating... …
```
> Fix azure_storage_queue Queue is not supported for the storage account closes #458

- azure/table_azure_compute_disk.go
<details>
```
N/A
```
</details>
<details>
```
> select name, network_access_policy from azure_compute_disk
+-----------------------------------------------------------+-----------------------+
| name                                                      | network_access_policy |
+-----------------------------------------------------------+-----------------------+
| newwarriors-AAA_OsDisk_1_eac82728fe9a4e58b3db75d0518dd24d | AllowAll              |
+-----------------------------------------------------------+-----------------------+
```
</details>
> Fix column network_access_policy in table azure_compute_disk closes #446

- azure/service.go
<details>
```
> select * from azure_key_vault
+----------------+---------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+--------------
| name           | id                                                                                                                              | vault_uri                               | type         
+----------------+---------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------+--------------
| rajsoftwarekey | /subscriptions/d46d7416-f95f-4771-bbb5-529d4c76659c/resourceGroups/steampipe/providers/Micros …
```
> Update GetNewSession method to properly handle the token

- azure/table_azure_subnet.go
<details>
```
SETUP: tests/azure_subnet []
PRETEST: tests/azure_subnet
TEST: tests/azure_subnet
azurerm_resource_group.named_test_resource: Creation complete after 4s [id=/subscriptions/d46d7416-f95f-4771-bbb5-529d4c76659c/resourceGroups/turbottest74455]
azurerm_virtual_network.named_test_resource: Creating...
azurerm_virtual_network.named_test_resource: Still creating... [10s elapsed] …
```
> Add column ip_configurations in the table azure_subnet closes #472

- azure-test/tests/azure_logic_app_workflow/test-list-query.sql
- azure/table_azure_logic_app_workflow.go
<details>
```
SETUP: tests/azure_logic_app_workflow []
PRETEST: tests/azure_logic_app_workflow
TEST: tests/azure_logic_app_workflow
azurerm_resource_group.named_test_resource: Creation complete after 5s [id=/subscriptions/f5t37416-f95f-4771-bbb5-529d4c76ef46/resourceGroups/turbottest70107]
azurerm_logic_app_workflow.named_test_resource: Creating...
azurerm_logic_app_workflow.named_test_resource: …
```
> Fix column access_control inconsistent state in table azure_logic_app_workflow closes #484

- azure/table_azure_app_service_web_app.go
<details>
```
Apply complete! Resources: 4 added, 0 changed, 0 destroyed.
Outputs:
principal_id = "**********************e9"
resource_aka = "azure:///subscriptions/**********************/resourceGroups/turbottest43751/providers/Microsoft.Web/sites/turbottest43751"
resource_aka_lower = "azure:///subscriptions/**********************/resourcegroups/turbottest43751/providers/microsoft.web/sites/turbottest43751"
resource_id = "/subscriptions/**********************/resourceGroups/turbottest43751/providers/Microsoft.Web/sites/turbottest43751"
resource_name = "turbottest43751"
subscription_id = "**********************"
tenant_id = "**********************"
Running SQL query: test-get-query.sql
[
{
"client_affinity_enabled": false,
"enabled": true,
"https_only": false,
"id": …
```
> Add column `diagnostic_logs_configuration` to table `azure_app_service_web_app` Closes #516

- docs/tables/azure_compute_disk_metric_read_ops.md
- docs/tables/azure_compute_disk_metric_read_ops_daily.md
- docs/tables/azure_compute_disk_metric_read_ops_hourly.md
- docs/tables/azure_compute_disk_metric_write_ops.md
- docs/tables/azure_compute_disk_metric_write_ops_daily.md
- docs/tables/azure_compute_disk_metric_write_ops_hourly.md
- docs/tables/azure_compute_virtual_machine_metric_cpu_utilization.md
- docs/tables/azure_compute_virtual_machine_metric_cpu_utilization_daily.md
- docs/tables/azure_compute_virtual_machine_metric_cpu_utilization_hourly.md
This PR fixes a documentation typo: several of the metric tables' docs refer to "GCP Monitoring", but I think they meant to refer to "Azure Monitor" instead.
> Docs: replace reference to 'GCP Monitoring' with 'Azure Monitor'

- azure/table_azure_app_configuration.go
… for table azure_app_configuration closes #529
<details>
```
SETUP: tests/azure_app_configuration []
PRETEST: tests/azure_app_configuration
TEST: tests/azure_app_configuration
+ create
+ resource "azurerm_app_configuration" "named_test_resource" {
+ endpoint            = (known after apply)
+ id                  = (known after apply)
+ location            = "westeurope"
+ …
```
> Fix nil pointer dereference error in azure_app_configuration table. Fixes#529

- azure/table_azure_cosmosdb_account.go
<details>
```
SETUP: tests/azure_cosmosdb_account []
PRETEST: tests/azure_cosmosdb_account
TEST: tests/azure_cosmosdb_account
data.azurerm_client_config.current: Read complete after 0s [id=Y2xpZW50Q29uZmlncy9jbGllbnRJZD0wNGIwNzc5NS04ZGRiLTQ2MWEtYmJlZS0wMmY5ZTFiZjdiNDY7b2JqZWN0SWQ9MDZmZDQ2YjAtYTg2Ny00OWExLWE0ZjEtZjc3Njg0NjVjYWJhO3N1YnNjcmlwdGlvbklkPWQ0NmQ3NDE2LWY5NWYtNDc3MS1iYmI1LTUyOWQ0Yzc2NjU5Yzt0ZW5hbnRJZD1jZGZmZDcwOC03ZGEwLTRjZWEtYWJlYi0wYTRjMzM0ZDdmNjQ=]
data.null_data_source.resource: Reading... …
```
> Fix column virtual_network_rules for table azure_cosmosdb_account closes #524

- azure/table_azure_app_service_plan.go
<details>
```
SETUP: tests/azure_app_service_plan []
PRETEST: tests/azure_app_service_plan
TEST: tests/azure_app_service_plan
data.azurerm_client_config.current: Read complete after 0s [id=Y2xpZW50Q29uZmlncy9jbGllbnRJZD0wNGIwNzc5NS04ZGRiLTQ2MWEtYmJlZS0wMmY5ZTFiZjdiNDY7b2JqZWN0SWQ9MDZmZDQ2YjAtYTg2Ny00OWExLWE0ZjEtZjc3Njg0NjVjYWJhO3N1YnNjcmlwdGlvbklkPWQ0NmQ3NDE2LWY5NWYtNDc3MS1iYmI1LTUyOWQ0Yzc2NjU5Yzt0ZW5hbnRJZD1jZGZmZDcwOC03ZGEwLTRjZWEtYWJlYi0wYTRjMzM0ZDdmNjQ=]
data.null_data_source.resource: Reading... …
```
> Add app details in table azure_app_service_plan closes #535

- docs/index.md
<details>
```
```
</details>
<details>
```
```
</details>
> Update docs/index.md file to include multi-subscription examples closes #519

- azure/service.go
- azure/table_azure_app_service_plan.go
- azure/table_azure_compute_resource_sku.go
<details>
```
lalit@Lalits-MacBook-Pro:~/WORK/Turbot/steampipe/plugins/steampipe-plugin-azure|main⚡ ⇒  steampipe query
Welcome to Steampipe v0.18.0-dev.0
For more information, type .help
> select * from azure_compute_disk
+------+----+------+--------------------+------------+----------+----------+--------------+-----------+----------------+-----------------+--------------+------------+--------------------+---------------------+---->
| name | id | type | provisioning_state | managed_by | sku_name | sku_tier | time_created | unique_id | disk_access_id | disk_size_bytes | disk_size_gb | disk_state | hyper_v_generation | disk_iops_read_only | dis>
+------+----+------+--------------------+------------+----------+----------+--------------+-----------+----------------+- …
```
> Fix ExpiredAuthenticationToken errors when using Azure CLI credentials. Fixes #521

- azure/table_azure_subnet.go
<details>
```
SETUP: tests/azure_subnet []
PRETEST: tests/azure_subnet
TEST: tests/azure_subnet
azurerm_resource_group.named_test_resource: Creation complete after 4s [id=/subscriptions/d46d7416-f95f-4771-bbb5-529d4c76659c/resourceGroups/turbottest74455]
azurerm_virtual_network.named_test_resource: Creating...
azurerm_virtual_network.named_test_resource: Still creating... [10s elapsed] …
```
> Getting ResourceNotFound error in table azure_subnet closes #555

- azure/table_azure_sql_database.go
<details>
```
SETUP: tests/azure_sql_database []
PRETEST: tests/azure_sql_database
TEST: tests/azure_sql_database
data.azurerm_client_config.current: Read complete after 0s [id=Y2xpZW50Q29uZmlncy9jbGllbnRJZD0wNGIwNzc5NS04ZGRiLTQ2MWEtYmJlZS0wMmY5ZTFiZjdiNDY7b2JqZWN0SWQ9MDZmZDQ2YjAtYTg2Ny00OWExLWE0ZjEtZjc3Njg0NjVjYWJhO3N1YnNjcmlwdGlvbklkPWQ0NmQ3NDE2LWY5NWYtNDc3MS1iYmI1LTUyOWQ0Yzc2NjU5Yzt0ZW5hbnRJZD1jZGZmZDcwOC03ZGEwLTRjZWEtYWJlYi0wYTRjMzM0ZDdmNjQ=]
data.null_data_source.resource: Reading... …
```
> Fixed VulnerabilityAssessmentInvalidPolicy error for table azure_sql_database closes #551

- azure/table_azure_mysql_server.go
- docs/tables/azure_mysql_server.md
<details>
```
SETUP: tests/azure_mysql_server []
PRETEST: tests/azure_mysql_server
TEST: tests/azure_mysql_server
azurerm_resource_group.named_test_resource: Creation complete after 2s [id=/subscriptions/********-****-****-****-************/resourceGroups/turbottest34770]
azurerm_mysql_server.named_test_resource: Creating...
azurerm_mysql_server.named_test_resource: Still creating... [10s elapsed] …
```
> Add VNET rules in table azure_mysql_server closes #557

- azure/table_azure_firewall.go
When ipConfigurations data is null on azure firewall steampipe throwns an error:
```
ERROR:  rpc error: code = Unknown desc = failed to populate column
'ip_configurations': rpc error: code = Internal desc = transform
ipConfigurationData failed with panic runtime error: invalid memory
address or nil pointer dereference
````
A json dump of the firewall resource shows:
```
"ipConfigurations": null
```
<details>
```
```
</details>
<details>
```
```
</details>
> Avoid panic when ip_configuration data on firewall is null

- azure/table_azure_compute_virtual_machine_scale_set_network_interface.go
fix typo in azure_compute_virtual_machine_scale_set_network_interface
> fix column name typo

- azure-test/tint.js
<details>
```
```
</details>
<details>
```
```
</details>
> Fix tint.js to remove the unused `variablesTmp` variable

- azure/table_azure_cosmosdb_account.go
- docs/tables/azure_cosmosdb_account.md
<details>
```
N/A
```
</details>
<details>
```sql
> select
name,
region,
backup_policy -> 'periodicModeProperties' ->> 'backupIntervalInMinutes' as backup_interval_mins,
backup_policy -> 'periodicModeProperties' ->> 'backupRetentionIntervalInHours' as backup_retention_interval_hrs,
backup_policy -> 'periodicModeProperties' ->> 'backupStorageRedundancy' as backup_storage_redundancy
from
azure_cosmosdb_account
where
backup_policy ->> 'type' = 'Periodic';
+---------------------+---------+----------------------+-------------------------------+---------------------------+
| name                | region  | backup_interval_mins | backup_retention_interval_hrs | backup_storage_redundancy | …
```
> Add column `backup_policy` to table `azure_cosmosdb_account`. Closes #584

- azure/table_azure_cosmosdb_account.go
- docs/tables/azure_cosmosdb_account.md
<details>
```
```
</details>
<details>
```
> select
name,
restore_parameters -> 'restoreMode' as restore_mode,
restore_parameters -> 'restoreSource' as restore_source,
d ->> 'databaseName' as restored_database_name,
c as restored_collection_name
from
azure_cosmosdb_account,
jsonb_array_elements(restore_parameters -> 'databasesToRestore') d,
jsonb_array_elements_text(d -> 'collectionNames') c;
+-------------------+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------+--------------------------+
| name              | restore_mode  | restore_source …
```
> Add column `restore_parameters` to table `azure_cosmosdb_account`. Closes #593

- azure/plugin.go
- azure/table_azure_app_service_web_app_slot.go
- docs/tables/azure_app_service_web_app_slot.md
<details>
```
```
</details>
<details>
```
+-------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------+---------------------------+------------------------+-------------------------------------+-------------+---------+--------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+----------+---------+-----------------------+---------- …
```
> Add table azure_app_service_web_app_slot. closes #567

- azure/table_azure_cosmosdb_mongo_collection.go
- azure/table_azure_cosmosdb_mongo_database.go
The table rendering used to break when using the `default` Throughput settings and `ThroughputPolicy` was not set explicitly.
{
"throughput_settings": {
"AutoscaleSettingsMaxThroughput": 1000,
"AutoscaleSettingsTargetMaxThroughput": 0,
"AutoscaleSettingsThroughputPolicy": `{}`,
"ID": `"/subscriptions/abcd7416-f95f-4771-bbb5- 529d4c76659c/resourceGroups/demo/providers/Microsoft.DocumentDB/databaseAccounts/demo-insight-acc/mongodbDatabases/test-db/throughputSettings/default"`,
"Location": "",
"Name": "Nlrk",
"ResourceEtag": "",
"ResourceMinimumThroughput": "1000",
"ResourceOfferReplacePending": "",
"ResourceRid": "",
"ResourceThroughput": 100,
"ResourceTs": 0,
"Type": "Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/throughputSettings"
}
}
<details>
```
Add …
```
> Fix error on fetching throughput settings

- azure/table_azure_storage_account.go
- docs/tables/azure_storage_account.md
Add `status_of_primary` and `status_of_secondary` to `azure_storage_account` table
> Add `status_of_primary` and `status_of_secondary` to `azure_storage_account` table

- azure/table_azure_storage_account.go
- docs/tables/azure_storage_account.md
- go.mod
- go.sum
<details>
```
SETUP: tests/azure_storage_account []
PRETEST: tests/azure_storage_account
TEST: tests/azure_storage_account
+ create
+ id       = (known after apply)
+ location = "eastus"
+ name     = "turbottest33803"
+ tags     = (known after apply)
}
+ resource "azurerm_storage_account" "named_test_resource" {
+ access_tier                       = "Cool"
+ account_encryption_source         = "Microsoft.Storage"
+ account_kind                      = "StorageV2"
+ account_replication_type          = "LRS"
+ …
```
> Add table service logging details in table azure_storage_account Closes #612

- azure/plugin.go
- azure/table_azure_kubernetes_service_version.go
- docs/tables/azure_kubernetes_service_version.md
<details>
```
N/A
```
</details>
<details>
```
> select
name,
id,
type,
orchestrator_type,
orchestrator_version
from
azure_kubernetes_service_version
where
region = 'eastus2';
+---------+--------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------->
| name    | id                                                                                                                       | type                                               | orchestrator_ty>
+---------+--------------------------------------------------------------------------------------------------------------------------+----------------------------- …
```
> Add table azure_kubernetes_service_version Closes #606

- azure/table_azure_mariadb_server.go
<details>
```
SETUP: tests/azure_mariadb_server []
PRETEST: tests/azure_mariadb_server
TEST: tests/azure_mariadb_server
azurerm_resource_group.named_test_resource: Creation complete after 2s [id=/subscriptions/********-****-****-****-************/resourceGroups/turbottest54160]
azurerm_mariadb_server.named_test_resource: Creating...
azurerm_mariadb_server.named_test_resource: Still creating... [10s …
```
> Fixed On querying private_endpoint_connections from table azure_mariadb_server it gives {} as result Closes #630

- azure/table_azure_kusto_cluster.go
- docs/tables/azure_kusto_cluster.md
<details>
```
```
</details>
<details>
```sql
select
name,
id,
state
from
azure_kusto_cluster
where
identity ->> 'type' = 'SystemAssigned';
+--------------+------------------------------------------------------------------------------------------------------------------------------------------------+----------+
| name         | id                                                                                                                                             | state    |
+--------------+------------------------------------------------------------------------------------------------------------------------------------------------+----------+
| cluster-test | …
```
> Add identity column to azure_kusto_cluster table closes #647

- azure/table_azure_postgresql_server.go
<details>
```
```
</details>
<details>
```
select server_security_alert_policy, title from azure_postgresql_server
+----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+
| server_security_alert_policy                                                                                                                                   | title                             |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------- …
```
> Add server_security_alert_policy column to azure_postgresql_server table closes #650

- azure/table_azure_app_service_web_app_slot.go
<details>
```
```
</details>
<details>
```
select name,app_name, resource_group, site_config_resource from azure_app_service_web_app_slot where name = 'slot-1' and app_name = 'web-app-test-mr' and resource_group = 'demo'
[
{
"app_name": "web-app-test-mr",
"name": "slot-1",
"resource_group": "demo",
"site_config_resource": {
"alwaysOn": false,
"appCommandLine": "",
"autoHealEnabled": false,
"defaultDocuments": [
"Default.htm",
"Default.html",
"Default.asp",
"index.htm",
"index.html",
"iisstart.htm",
"default.aspx",
"index.php",
"hostingstart.html"
],
"detailedErrorLoggingEnabled": false,
"experiments": {
"rampUpRules": []
},
"ftpsState": "FtpsOnly",
"http20Enabled": false,
"httpLoggingEnabled": false, …
```
> Fix the GetConfig of azure_app_service_web_app_slot table to correctly return data instead of an empty row

- azure/table_azure_app_service_web_app.go
- docs/tables/azure_app_service_web_app.md
<details>
```
```
</details>
<details>
```sql
> select storage_info_value from azure_app_service_web_app
[
{
"storage_info_value": {
"properties": {
"storage-mount-info": {
"accessKey": "I01jGbfjfoP7wg3Y6V+bXCWQUlpfqlW0Z1111111NrFOqLndq+VTyIwacIJJ1X2XXqwVbDfMZKs3LBjFtCIMlcFQ==",
"accountName": "testimmutablecontainer",
"mountPath": "/H",
"shareName": "container-m",
"type": "AzureBlob"
}
}
}
}
]
```
```sql
> select name, storage_info_value from azure_app_service_web_app where resource_group = 'demo' and name = 'web-app-test-storage-info'
[
{
"name": "web-app-test-storage-info",
"storage_info_value": {
"properties": {
"storage-mount-info": {
"accessKey": …
```
> Add storage_info_value column to azure_app_service_web_app table closes #646

- azure/table_azure_mysql_server.go
- docs/tables/azure_mysql_server.md
<details>
```
```
</details>
<details>
```sql
select
name,
id,
type,
server_security_alert_policy
from
azure_mysql_server
where
resource_group = 'demo'
and name = 'server-test-for-pr';
[
{
"id": "/subscriptions/d46d7416-1111-4771-1111-529d4c11111v/resourceGroups/demo/providers/Microsoft.DBforMySQL/servers/server-test-for-pr",
"name": "server-test-for-pr",
"server_security_alert_policy": {
"disabledAlerts": [
""
],
"emailAccountAdmins": false,
"emailAddresses": [
""
],
"retentionDays": 0,
"state": "Enabled",
"storageAccountAccessKey": "",
"storageEndpoint": ""
},
"type": "Microsoft.DBforMySQL/servers"
}
]
```
</details>
> Add server_security_alert_policy column to azure_mysql_server table closes #649

- azure/plugin.go
- azure/table_azure_databricks_workspace.go
- docs/tables/azure_databricks_workspace.md
<details>
```
```
</details>
<details>
```sql
select
name,
id,
workspace_id,
workspace_url,
created_date_time,
sku
from
azure_databricks_workspace;
+----------------+----------------------------------------------------------------------------------------------------------------------------------------------------+------------------+---------------------------------------------+---------------------------+--------------------+
| name           | id                                                                                                                                                 | workspace_id     | workspace_url                               | created_date_time         | sku …
```
> Add table azure_databricks_workspace. Closes #691.

- azure/table_azure_servicebus_namespace.go
<details>
```sql
select title, status, disable_local_auth  from  azure_servicebus_namespace
+--------------------+--------+--------------------+
| title              | status | disable_local_auth |
+--------------------+--------+--------------------+
| az-compliance-test | Active | true               |
+--------------------+--------+--------------------+
```
</details>
> Add column status and disable_local_auth in table azure_servicebus_namespace. Closes #714

- azure/table_azure_key_vault_secret.go
- docs/tables/azure_key_vault_secret.md
<details>
```
SETUP: tests/azure_key_vault_secret []
PRETEST: tests/azure_key_vault_secret
TEST: tests/azure_key_vault_secret
azurerm_resource_group.named_test_resource: Refreshing state... [id=/subscriptions/3510ae4d-530b-497d-8f30-53b9616fc6c1/resourceGroups/turbottest86537]
data.azurerm_client_config.current: Read complete after 0s [id=Y2xpZW50Q29uZmlncy9jbGllbnRJZD0wNGIwNzc5NS04ZGRiLTQ2MWEtYmJlZS0wMmY5ZTFiZjdiNDY7b2JqZWN0SWQ9MDZmZDQ2YjAtYTg2Ny00OWExLWE0ZjEtZjc3Njg0NjVjYWJhO3N1YnNjcmlwdGlvbklkPWQ0NmQ3NDE2LWY5 …
```
> Fixed azure_key_vault_secret crashes when keyvault name is camel-case Closes #637

- azure/table_azure_sql_database.go
- azure/table_azure_sql_server.go
<details>
```
```
</details>
<details>
```
> select name, jsonb_pretty(audit_policy) from azure_sql_database
+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name      | jsonb_pretty                                                                                                                                                                      |
+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| test-db23 | [ …
```
> Add audit_policy detail in table azure_sql_database and azure_sql_server Closes #709

- azure/table_azure_cosmosdb_account.go
<details>
```
```
</details>
<details>
```
select
a.id as resource,
case
when disable_local_auth then 'ok'
else 'alarm'
end as status,
case
when disable_local_auth then a.name || ' is using AAD and RBAC.'
else a.name || ' is not using AAD and RBAC.'
end as reason
from
azure_cosmosdb_account as a,
azure_subscription as sub
where
sub.subscription_id = a.subscription_id;
[
{
"reason": "turbot-test-20200125-create-update is using AAD and RBAC.",
"resource": "/subscriptions/dddddddd-bbbb-7777777777c/resourceGroups/turbot-test-20200125-create-update/providers/Microsoft.DocumentDB/databaseAccounts/turbot-test-20200125-create-update",
"status": "ok"
}
]
```
</details>
> Add column `disable_local_auth` to table `azure_cosmosdb_account`. Closes #735

- azure/table_azure_postgresql_flexible_server.go
<details>
```
N/A
```
</details>
<details>
```
> select name, jsonb_pretty(server_properties) from azure_postgresql_flexible_server
+--------+-----------------------------------------------------------------------+
| name   | jsonb_pretty                                                          |
+--------+-----------------------------------------------------------------------+
| test63 | {                                                                     |
|        |     "Tags": null,                                                     |
|        |     "State": "Ready",                                                 |
|        |     "Backup": {                                                       |
|        | …
```
> Fixed azure_postgresql_flexible_server does not appear to provide fullyQualifiedDomainName Closes #753

- azure/table_azure_application_insight.go
<details>
```
When it was json column:-
select public_network_access_for_ingestion,public_network_access_for_query from azure_application_insight
+-------------------------------------+---------------------------------+
| public_network_access_for_ingestion | public_network_access_for_query |
+-------------------------------------+---------------------------------+
| "Enabled"                           | "Enabled"                       |
+-------------------------------------+---------------------------------+
After changing the column type to string:-
select public_network_access_for_ingestion,public_network_access_for_query from azure_application_insight
+-------------------------------------+---------------------------------+
| …
```
> Update incorrect Column Type for Network Access Fields in azure_application_insight Table. Closes #768

- azure/table_azure_application_gateway.go
<details>
```
```
</details>
<details>
```
> select name, jsonb_pretty(web_application_firewall_configuration) from azure_application_gateway;
+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| name     | jsonb_pretty                                                                                                                                             |
+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| test2223 | <null> …
```
> Fixed missing web_application_firewall_configuration details in table azure_application_gateway Closes #765

- azure/table_azure_role_assignment.go
- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
> select
name,
principal_id,
principal_type
from
azure_role_assignment;
+--------------------------------------+--------------------------------------+------------------+
| name                                 | principal_id                         | principal_type   |
+--------------------------------------+--------------------------------------+------------------+
| b4596e75-b6c9-46b6-8b7d-cce52ac49495 | 92f0bf94-4e47-41ea-bc68-5e97c5a3f9ff | User             |
| 86a52481-d93a-4db1-bd65-0418a21838ed | 7bafb0a2-eee8-48c6-81ec-039836536d96 | Group            |
| 6c21b1b1-bb25-42b1-8b9f-bf4b151eefc3 | 5466f530-deaa-4e3f-82cc-fb9dffb59444 | ServicePrincipal | …
```
> Fixed the table azure_role_assignment for populating the column value correctly Closes #759

- azure/table_azure_subscription.go
<details>
```
SETUP: tests/azure_subscription []
PRETEST: tests/azure_subscription
TEST: tests/azure_subscription
data.azuread_client_config.current: Reading...
data.azuread_client_config.current: Read complete after 0s [id=cdffd708-7da0-4cea-abeb-0a4c334d7f64-04b07795-8ddb-461a-bbee-02f9e1bf7b46-06fd46b0-a867-49a1-a4f1-f7768465caba]
data.azurerm_subscription.current: Reading...
data.azurerm_subscription.current: Read complete after 1s [id=/subscriptions/********-****-****-****-************]
Changes to Outputs:
+ current_subscription_display_name = …
```
> Added column tags in azure_subscription table Closes #783

- azure/table_azure_storage_account.go
<details>
```
```
</details>
<details>
```
> select title, public_network_access from azure_storage_account
+------------------------+-----------------------+
| title                  | public_network_access |
+------------------------+-----------------------+
| test883                | Enabled               |
| testimmutablecontainer | Disabled              |
| test732                | Enabled               |
| tets566                | Enabled               |
+------------------------+-----------------------+
> 
```
</details>
> Add public_network_access column in table azure_storage_account

- azure/table_azure_log_alert.go
<details>
```
```
</details>
<details>
```
> select name, enabled, description, scopes, condition from azure_log_alert
+----------------+---------+-------------+---------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------->
| name           | enabled | description | scopes                                                  | condition                                                                                                                             >
+----------------+---------+-------------+---------------------------------------------------------+----------------- …
```
> Fixed column scopes and condition in table azure_log_alert Closes #795

- azure/table_azure_compute_virtual_machine.go
- azure/table_azure_compute_virtual_machine_scale_set_vm.go
- docs/tables/azure_compute_virtual_machine_scale_set_vm.md
This PR add power state to the `azure_compute_virtual_machine_scale_set_vm` table.
Largely inspired from the code of the `azure_compute_virtual_machine` table.
> feat: add power state to VMSS virtual machines

- azure/plugin.go
- azure/table_azure_resource.go
- docs/tables/azure_resource.md
<details>
```
N/A
```
</details>
<details>
```
> SELECT 
name, 
type, 
region, 
identity_principal_id, 
plan_publisher, 
plan_name, 
plan_product, 
plan_promotion_code, 
plan_version, 
resource_group, 
tags 
FROM 
azure_resource 
WHERE 
filter = 'startswith(tagName, ''cost'')'
+------------------------+-----------------------------------+-----------+--------------------------------------+----------------+-----------+--------------+---------------------+--------------+-----------------+----------------------->
| name                   | type                              | region    | identity_principal_id                | plan_publisher | plan_name | plan_product | plan_promotion_code | plan_version | resource_group  | tags …
```
> Add table azure_resource Closes #792

- azure/table_azure_compute_virtual_machine.go
<details>
```
N/A
```
</details>
<details>
```
> select name, power_state from azure_compute_virtual_machine
+-----------------+-------------+
| name            | power_state |
+-----------------+-------------+
| tets-delete     | deallocated |
| test-power      | running     |
| turbottest95054 | running     |
+-----------------+-------------+
```
</details>
> Fixed the error invalid memory address or nil pointer dereference for the column `power_state` in the table azure_compute_virtual_machine

- azure/table_azure_compute_virtual_machine.go
- go.mod
- go.sum
<details>
```
```
</details>
<details>
```
Gov Cloud:
> select name, jsonb_pretty(guest_configuration_assignments) from azure_compute_virtual_machine
Warning: Server enforces maximum TTL of 300 seconds. Cannot set TTL to 900 seconds. TTL set to 300 seconds.
+--------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
| name               | jsonb_pretty …
```
> Fix azure_compute_virtual_machine table to correctly populate guest_configuration_assignments column across all Azure environments. Closes #812

- azure-test/tests/azure_subnet/test-get-expected.json
- azure/table_azure_subnet.go
<details>
```
SETUP: tests/azure_subnet []
PRETEST: tests/azure_subnet
TEST: tests/azure_subnet
data.azurerm_client_config.current: Read complete after 0s [id=Y2xpZW50Q29uZmlncy9jbGllbnRJZD0wNGIwNzc5NS04ZGRiLTQ2MWEtYmJlZS0wMmY5ZTFiZjdiNDY7b2JqZWN0SWQ9MDZmZDQ2YjAtYTg2Ny00OWExLWE0ZjEtZjc3Njg0NjVjYWJhO3N1YnNjcmlwdGlvbklkPWQ0NmQ3NDE2LWY5NWYtNDc3MS1iYmI1LTUyOWQ0Yzc2NjU5Yzt0ZW5hbnRJZD1jZGZmZDcwOC03ZGEwLTRjZWEtYWJlYi0wYTRjMzM0ZDdmNjQ=]
data.null_data_source.resource: Reading...
data.null_data_source.resource: Read …
```
> Fixed the table `azure_subnet` to correctly populate the `ip_configurations` column value Closes #815

- azure/table_azure_compute_virtual_machine.go
<details>
```
```
</details>
<details>
```
select name, statuses, time_created from azure_compute_virtual_machine
{
"rows": [
{
"name": "test-delete-me",
"statuses": [
{
"code": "ProvisioningState/succeeded",
"displayStatus": "Provisioning succeeded",
"level": "Info",
"time": "2024-08-27T08:41:11.2737688Z"
},
{
"code": "PowerState/deallocated",
"displayStatus": "VM deallocated",
"level": "Info"
}
],
"time_created": "2024-08-27T14:06:36+05:30"
}
],
"metadata": {
"duration_ms": 2777,
"scans": null,
"scan_count": 1,
"rows_returned": 1,
"uncached_rows_fetched": 1,
"cached_rows_fetched": 0,
"hydrate_calls": 1,
"connection_count": 1
}
}
Time: 2.8s. Rows returned: 1. Rows fetched: 1. Hydrate calls: 1.
``` …
> Add column time_created to azure_compute_virtual_machine table closes #830

- azure/table_azure_compute_virtual_machine.go
- azure/table_azure_compute_virtual_machine_scale_set.go
- azure/table_azure_compute_virtual_machine_scale_set_vm.go
If VMs are managed by VMSS in flexible orchestration mode, the standard VM API must be used: https://learn.microsoft.com/en-us/answers/questions/1418158/rest-api-request-returns-badrequest-for-vmss
Without this change, the following error occurs when trying to read `power_state` of such VMs:
```
Error: azure: compute.VirtualMachineScaleSetVMsClient#GetInstanceView: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidParameter" Message="Virtual Machine Scale Set VM instanceId must be a number." Target="instanceId" (SQLSTATE HV000)
+-------------+
| power_state |
+-------------+
+-------------+
```
With this change, this returns the power state properly:
```
+-------------+
| power_state |
+-------------+
| …
```
> fix: use standard API for Azure VMs in VMSS with flexible orchestration mode

- azure/table_azure_compute_disk.go
Needed for cis_v300 section 8.5 and 8.6
```
> select name, public_network_access, data_access_auth_mode from azure_compute_disk
+-----------------+-----------------------+-----------------------+
| name            | public_network_access | data_access_auth_mode |
+-----------------+-----------------------+-----------------------+
| disk-123        | Disabled              | AzureActiveDirectory  |
| turbottest76149 | Enabled               |                       |
+-----------------+-----------------------+-----------------------+
select
disk.id as resource,
case
when network_access_policy in ('DenyAll','AllowPrivate') and public_network_access = 'Disabled' then 'ok'
else 'alarm'
end as status,
case
when network_access_policy in ('DenyAll','AllowPrivate') and public_network_access = …
```
> Add column public_network_access and data_access_auth_mode to table azure_compute_disk. Closes #843

- azure/table_azure_postgresql_flexible_server.go
<details>
```
```
</details>
<details>
```
> select name, jsonb_pretty(firewall_rules) as firewall_rules from azure_postgresql_flexible_server
+---------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name    | firewall_rules                                                                                                                                                                                                                        |
+---------+-------------------------------------------------------------------- …
```
> Added column firewall_rule in the table azure_postgresql_flexible_server Closes #851

- azure/plugin.go
- azure/table_azure_compute_virtual_machine_size.go
- docs/tables/azure_compute_virtual_machine_size.md
- go.mod
- go.sum
<details>
```
N/A
```
</details>
<details>
```
> select * from azure_compute_virtual_machine_size
+---------------------------+-----------------+--------------------+--------------------------+--------------+---------------------+---------------------------+--------------------+-------------------+--------------------------------------+--------------------+----------------------------------------------------->
| name                      | number_of_cores | os_disk_size_in_mb | resource_disk_size_in_mb | memory_in_mb | max_data_disk_count | title                     | region             | cloud_environment | subscription_id                      | sp_connection_name | sp_ctx                                              > …
```
> Add table azure_compute_virtual_machine_size Closes #826

- azure/table_azure_mysql_flexible_server.go
<details>
```
```
</details>
<details>
**Before Fix:**  
```
> select name, state from azure_mysql_flexible_server;
+--------+---------+
| name   | state   |
+--------+---------+
| test53 | Stopped |
```
```
> select * from azure_mysql_flexible_server;
Error: azure: GET https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxx/resourceGroups/new-rg/providers/Microsoft.DBforMySQL/flexibleServers/test53/configurations
--------------------------------------------------------------------------------
RESPONSE 409: 409 Conflict
ERROR CODE: ServerUnavailableForOperation
--------------------------------------------------------------------------------
{
"error": {
"code": …
```
> Fixed azure_mysql_flexible_server fails when the server is stopped Closes #859

- azure/table_azure_role_assignment.go
- docs/tables/azure_role_assignment.md
<details>
```
```
</details>
<details>
```
> select scope, principal_id, principal_type from azure_role_assignment where scope like '%resourceGroups%';
+-------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+------------------+
| scope                                                                                                                                                 | principal_id                         | principal_type   |
+------------------------------------------------------------------------------------------------------------------------------------- …
```
> Fixed azure_role_assignment table to return all role assignments when scope is not specified in the query Closes #866

- docs/tables/azure_monitor_activity_log_event.md
Just a typo fix in the header of some markdown.
> Fix tiny typo: s/evens/events

- azure/table_azure_storage_account.go
<details>
```
```
</details>
<details>
```
> select name, key_policy from azure_storage_account
+------------------------+----------------------------------+
| name                   | key_policy                       |
+------------------------+----------------------------------+
| testcompliancemod      | <null>                           |
| premiumtable           | <null>                           |
| pyddgroup81fd          | <null>                           |
| testimmutablecontainer | <null>                           |
| testpremiumpartha      | {"keyExpirationPeriodInDays":60} |
| demob349               | {"keyExpirationPeriodInDays":60} |
| tets5666linuxgroupaf20 | <null> …
```
> Fixed table azure_storage_account throws no such host error for premium type storage account and added a new column key_policy Closes #919

- azure/table_azure_kubernetes_cluster.go
<details>
```
```
</details>
<details>
```
> select name, support_plan from azure_kubernetes_cluster
+----------------------+--------------------+
| name                 | support_plan       |
+----------------------+--------------------+
| bdai-poc-aks-weu-aks | KubernetesOfficial |
+----------------------+--------------------+
```
</details>
> feat: add support_plan to azure_kubernetes_cluster table
